---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3337745801-ojv0frFfd6UTUfQXq8EQ1IGliLNdS1gmVRo2vED
:access_token_secret: E08JUlDkXVCTRHBZelEeaQQlUUkgTHsuPpDnd3NuS0Vwi
